export const Strings = {
    PANDORAS_VAULT : 'Pandoras Vault',
    WELCOME_TO_PANDORAS_VAULT : 'Welcome to Pandoras Vault!',
    LOREM_IPSUM : ' Lorem ipsum dolor sit amet, consectetur adipiscing elit.In pulvinar ac justo vel molestie. Vivamus in mollis dolor. Mauris dapibus, justo sed consequat congue',
    YOU_MAY_UPGRADE_YOUR_REGISTRATION : 'You may upgrade your registration now to avail of the various features of the app',
    CONGRATS_YOUR_ACCOUNT_IS_NOW_ACTIVE : " Congratulations, your account is now active, you can start using the application",
    PLEASE_ENTER_6_DIGIT_CODE_TO_YOUR_PHONE  : 'Please enter the 6 - digit code we sent to your phone number',
    WE_SENT_YOU_AN_EMAIL : 'We sent you an Email Please enter the 6 - digit code below',
    YOUR_ACCOUNT_IS_NOW_ACTIVE : 'Your account is now active',
    DIDNT_RECEIVE_YOUR_CODE : "Didn’t receive your code?",
    OTP_VERIFICATION_SUCCESSFUL : 'OTP Verification successful',
    EMAIL_SEND_SUCCESSFULLY : 'Email Send Successfully',
    OTP_SENT_SUCCESSFULLY : 'OTP Send Successfully',
    QR_SHARED_SUCCESSFULLY : 'QR shared succesfully!!',
    QR_SAVED_SUCCESSFULLY : 'QR saved successfully!!',
    REGISTER_NEW_ACCOUNT : 'Register new account',
    USE_MOBILE_NUMBER_INSTEAD : 'Use mobile number instead?',
    USE_EMAIL_INSTEAD : 'Use email instead?',
    VALID_ID_CAPTURE : 'Valid ID Capture',
    SELFIE_CAPTURE : 'Selfie Capture',
    ADDITIONAL_INFO : 'Additional Information',
    CODE_VERIFICATION : 'Code verification',
    SHARE_MY_QR_CODE : 'Share my QR Code',
    SAVE_TO_MY_GALLERY : 'Save to My Gallery',
    I_AGREE_TO_TERMS_AND_PRIVACY_POLICY : 'I agree to the Terms and Conditions and Privacy Policy',
    PLEASE_ENTER_YOUR_USERNAME_AND_PASSWORD : 'Please enter your valid Username and Password',
    END_USER_LINCENSE_AND_AGREEMENTS : 'End User License and Agreements',
    EMAIL_CANT_BE_EMPTY :  "Email can't be empty!!",
    MOBILE_CANT_BE_EMPTY : "Mobile number can't be empty!!",
    FIRST_NAME_CANT_BE_EMPTY : "First name can't be empty!!",
    LAST_NAME_CANT_BE_EMPTY : "Last name can't be empty!!",
    USERNAME_CANT_BE_EMPTY : "Username can't be empty!!",
    PASSWORD_CANT_BE_EMPTY : "Password can't be empty!!",
    INPUT_FIELD_IS_EMPTY : "Input field is empty!!",
    NAME_MUST_CONTAIN_ALPHABETS_ONLY : "First,Middle and Last name must contain alphabets only!!",
    PASSWORD_AND_CONFIRM_PASSWORD_ARE_NOT_SAME : "Password and confirm password are not same!!",
    USERNAME_MUST_CONATIN_APLHABETS_NUMBERS_AND_UNDERSCORES : "Username can only contain alphabets,numbers and underscores.",
    PASSWORD_SHOULD_BE_8_CHARACTERS_LONG : "Password should be 8 characters long.It must contain uppercase,lowercase,special characters and numbers",
    EMAIL_ADDRESS_IS_NOT_VALID  : "Email address is not valid!!",
    MOBILE_MUST_BE_OF_10_DIGITS :  "Mobile number must be of 10 digits.It must be preceded with country code. (e.g. +91 for India)",
    SWITCH_ACCOUNT : 'Switch account',
    FORGOT_PASSOWRD : 'Forgot Password?',
    NO_ACCOUNT : 'No Account?',
    QUICK_VIEW : 'Quick View',
    FIRST_NAME : 'First name',
    MIDDLE_NAME  : 'Middle name',
    LAST_NAME : 'Last name',
    USERNAME : 'Username',
    USER_NAME : 'User name',
    MOBILE_PHONE : 'Mobile phone',
    PASSWORD : 'Password',
    CONFIRM_PASSWORD : 'Confirm password',
    EMAIL : 'Email',
    STEP_1 : 'Step 1',
    STEP_2 : 'Step 2',
    STEP_3 : 'Step 3',
    CANCEL : 'Cancel',
    SIGN_UP : 'Sign up',
    SIGN_IN : 'Sign In',
    NEXT : 'Next',
    CASH_IN : 'Cash In',
    ONLINE_BANKING : 'Online Banking',
    VIEW_ALL : 'View All',
    MAKE_YOUR_TRANSACTIONS_QUICK_AND_EASY : "Make your transactions quick and easy.",
    VIRTUAL_IS_THE_NEW_NORMAL : "Virtual is the new normal.",
    ONER_THE_COUNTER : "Over the Counter",
    CASH_IN_WITH_EASE : "Cash in with ease.",
    E_WALLETS : 'E-wallets',
    CURRENT_BALANCE : "Current Balance",
    PROCESSING_TIME : "Processing Time",
    CASH_IN_AMOUNT : "Cash in Amount",
    FEES  : "Fees",
    TOTAL : "Total",
    AMOUNT : "Amount",
    ORDER_NUMBER : "Order Number",
    DEPOSIT_AMOUNT : "Deposit Amount",
    PAYMENT_DEADLINE  : "Payment Deadline",
    PAY_WITH_DRAGON_PAY  : "Pay With Dragon Pay",
    HASSLE_FREE_ONLINE_ANYTIME : "Hassle-free online anytime.",
    REMITTANCE :  "Remittance",
    PANDORAS_VAULT_MERCHANT : "Pandoras Vault Merchant",
    CASH_OUT : "Cash Out",
    CASH_OUT_VIA : "Cash Out via",
    METHOD : "Method",
    SELECT_FROM : "Select from"
}