# Generated by Django 2.2.28 on 2022-12-23 07:26

from django.db import migrations, models
import home.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221213_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, storage=home.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
