# Generated by Django 2.2.28 on 2023-01-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221223_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='subwallet_name',
            new_name='wallet_name',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.AddField(
            model_name='wallet',
            name='blockchain_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='wallet',
            name='crypto_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ethereum'), (2, 'Bitcoin'), (3, 'USDT'), (4, 'USDC'), (5, 'REDLC')], null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_subwallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Blockchain'), (2, 'Fiat')], default=2),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_type', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=((1, 'Online-Bank'), (2, 'E-Wallet'), (3, 'Over-The-Counter')))),
                ('is_external_transaction', models.BooleanField(default=False)),
                ('transaction_amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('remaining_balance', models.DecimalField(decimal_places=10, max_digits=19)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
